Update hs-test-python to v10.0.1 and hs-test to v10.0.3 versions for epicbox-hyperskill
StepicOrg/epicbox-images pull request #72
Opened 2023-04-12 12:16 UTC by polischuks

@meanmail updated  hs-test-python to v10.0.1 and hs-test to v10.0.3 version in the images.

2023-04-17 07:20 UTC, meanmail commented on epicbox-hyperskill/go/Dockerfile
> +    https://github.com/hyperskill/hs-test/releases/download/v10.0.3/hs-test-10.0.3.jar
Line 6: Update hs-test-python

2023-04-19 09:41 UTC, meanmail requested changes
https://github.com/StepicOrg/epicbox-images/pull/72#discussion_r1168279131

2023-04-19 10:16 UTC, polischuks commented on epicbox-hyperskill/go/Dockerfile
> +    https://github.com/hyperskill/hs-test/releases/download/v10.0.3/hs-test-10.0.3.jar
done.

2023-04-21 07:39 UTC, meanmail approved these changes

2023-04-21 07:40 UTC, merged