Install libraries in epicbox-hyperskill/go
StepicOrg/epicbox-images pull request #75
Opened 2023-04-19 16:56 UTC by polischuks

[HSPC-69](https://vyahhi.myjetbrains.com/youtrack/issue/HSPC-69/Install-libraries-in-epicbox-hyperskill-go)

2023-04-21 07:48 UTC, meanmail commented on epicbox-hyperskill/go/Dockerfile
> +WORKDIR /checker
Рабочую директорию, наверное, не нужно менять. Или в конце Dockerfile вернуть исходную

2023-04-21 09:08 UTC, polischuks commented on epicbox-hyperskill/go/Dockerfile
> +WORKDIR /checker
done

2023-04-21 17:32 UTC, meanmail requested changes

2023-04-21 17:32 UTC, meanmail commented on epicbox-hyperskill/go/Dockerfile
> +WORKDIR /
```bash
docker run golang:1.18-alpine pwd
/go
```

```suggestion
WORKDIR /go
```

2023-04-26 13:04 UTC, meanmail approved these changes

2023-04-26 13:04 UTC, merged